name: Build ACE-RFID (macOS Universal)

on:
  push:
    branches: [ macos ]
  pull_request:
    branches: [ macos ]

jobs:
  build:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew update
          brew install autoconf automake libtool pkg-config

      - name: Build libnfc for x86_64
        run: |
          git clone https://github.com/nfc-tools/libnfc.git
          cd libnfc
          autoreconf -vis || true
          export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
          export CC="clang -arch x86_64 -isysroot $SDKROOT"
          ./configure --host=x86_64-apple-darwin --prefix=$GITHUB_WORKSPACE/libnfc_x86_64
          make
          make install

      - name: Build libnfc for arm64
        run: |
          cd libnfc
          make clean
          export CC="clang -arch arm64 -isysroot $SDKROOT"
          ./configure --host=arm-apple-darwin --prefix=$GITHUB_WORKSPACE/libnfc_arm64
          make
          make install

      - name: Create universal libnfc
        run: |
          lipo -create $GITHUB_WORKSPACE/libnfc_x86_64/lib/libnfc.6.dylib $GITHUB_WORKSPACE/libnfc_arm64/lib/libnfc.6.dylib -output $GITHUB_WORKSPACE/libnfc_universal.dylib

      - name: Build ACE-RFID.xcodeproj (Universal)
        run: |
          export LIBRARY_SEARCH_PATHS="$GITHUB_WORKSPACE"
          xcodebuild -project MacOS/ACE-RFID.xcodeproj -scheme ACE-RFID -configuration Release ARCHS="x86_64 arm64" ONLY_ACTIVE_ARCH=NO

      - name: Archive app
        run: |
          xcodebuild -project MacOS/ACE-RFID.xcodeproj -scheme ACE-RFID -configuration Release -archivePath $GITHUB_WORKSPACE/ACE-RFID.xcarchive archive

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ACE-RFID-macOS-build
          path: $GITHUB_WORKSPACE/ACE-RFID.xcarchive
